"""empty message

Revision ID: 0fb0c230b0a5
Revises: 1d33547701ba
Create Date: 2019-05-14 21:46:48.259476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb0c230b0a5'
down_revision = '1d33547701ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vk_groups',
    sa.Column('url_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('url_name')
    )
    op.create_table('chat_and_vk_group',
    sa.Column('chats_chat_id', sa.Integer(), nullable=True),
    sa.Column('vk_groups_url_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chats_chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['vk_groups_url_name'], ['vk_groups.url_name'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_and_vk_group')
    op.drop_table('vk_groups')
    # ### end Alembic commands ###
