"""empty message

Revision ID: 5d67cfc20105
Revises: 
Create Date: 2019-04-29 02:15:35.713219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d67cfc20105'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_and_chat',
    sa.Column('chats_chat_id', sa.Integer(), nullable=True),
    sa.Column('users_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chats_chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['users_user_id'], ['users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_and_chat')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
