"""empty message

Revision ID: 9c628daec881
Revises: 0fb0c230b0a5
Create Date: 2019-05-15 00:09:47.321675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c628daec881'
down_revision = '0fb0c230b0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vk_creds',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vk_creds')
    # ### end Alembic commands ###
