"""empty message

Revision ID: c58fb194c34b
Revises: 9c628daec881
Create Date: 2020-04-29 18:11:17.154517

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c58fb194c34b'
down_revision = '9c628daec881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'chat_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.BigInteger(),
                    autoincrement=True,
                    existing_server_default=sa.text("nextval('chats_chat_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'chat_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.INTEGER(),
                    autoincrement=True,
                    existing_server_default=sa.text("nextval('chats_chat_id_seq'::regclass)"))
    # ### end Alembic commands ###
